# Generated by Django 5.2 on 2025-05-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_userprojectactivity_option_bot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='is_active',
        ),
        migrations.CreateModel(
            name='BotLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('label_color', models.CharField(max_length=7)),
                ('label_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
            ],
        ),
        migrations.CreateModel(
            name='BotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=20)),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.bot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectBot',
        ),
    ]
